import { createSlice } from "@reduxjs/toolkit";

const databaseSlice = createSlice({
  name: "database",
  initialState: {
    error: "",
    paymentNotificationItem: "",
    paymentNotifications: [
      {
        id: 1,
        pspreference: "",
        timestamp: "",
        eventcode: "",
        merchantaccount: "",
        notification: "",
        merchantreference: "",
        shopperreference: "",
      },
    ],
    paymentNotificationsExample: [
      {
        id: 21,
        pspreference: "X6LXC5ZMHV5X8N82",
        timestamp: "2023-02-12T17:45:07.150+00:00",
        eventcode: "AUTHORISATION",
        merchantaccount: "DemoStore",
        notification: {
          additionalData: {
            "fraudCheck-25-CVCAuthResultCheck": "0",
            "fraudCheck-75-PaymentDetailCarteBancaireRefCheck": "0",
            "fraudCheck-72-TransactionTimeCheck": "0",
            refusalReasonRaw: "AUTHORISED",
            eci: "07",
            threeDSVersion: "1.0.2",
            acquirerAccountCode: "TestPmmAcquirerAccount",
            "fraudCheck-8-ShopperEmailUsage": "1",
            xid: "N/A",
            threeDAuthenticated: "false",
            "fraudCheck-2-CardChunkUsage": "1",
            issuerBin: "41111111",
            payoutEligible: "Y",
            "fraudCheck-77-EmailSyntaxCheck": "0",
            fraudManualReview: "false",
            threeDOffered: "true",
            "fraudCheck-3-PaymentDetailUsage": "1",
            threeDOfferedResponse: "U",
            authorisationMid: "50",
            "checkout.cardAddedBrand": "visa",
            "fraudCheck-7-ShopperIpUsage": "0",
            cavv: "N/A",
            fundsAvailability: "I",
            authorisedAmountCurrency: "EUR",
            threeDAuthenticatedResponse: "N/A",
            "threeds2.cardEnrolled": "false",
            avsResultRaw: "5",
            "retry.attempt1.rawResponse": "AUTHORISED",
            paymentMethod: "visa",
            avsResult: "5 No AVS data provided",
            "fraudCheck-41-PaymentDetailNonFraudRefCheck": "50",
            cardSummary: "1111",
            "retry.attempt1.avsResultRaw": "5",
            networkTxReference: "679446487644521",
            totalFraudScore: "53",
            hmacSignature: "RUjyyCAd2UmNiL1mgDggl6n48k+LvmlSRQU6BvFAeHc=",
            expiryDate: "03/2030",
            "fraudCheck-65-EmailDomainRefCheck": "0",
            "fraudCheck-15-IssuingCountryReferral": "0",
            cavvAlgorithm: "N/A",
            "fraudCheck-26-ShopperEmailRefCheck": "0",
            cardBin: "411111",
            cvcResultRaw: "M",
            "fraudCheck-4-HolderNameUsage": "0",
            merchantReference: "b78ea8cc-b86b-431f-9605-12437f052332",
            acquirerReference: "2XSSWMLS2R8",
            "fraudCheck-13-IssuerRefCheck": "0",
            cardIssuingCountry: "NL",
            liabilityShift: "false",
            fraudResultType: "GREEN",
            authCode: "074723",
            cardHolderName: "Checkout Shopper PlaceHolder",
            isCardCommercial: "unknown",
            PaymentAccountReference: "kB6v8xDYudKQGu6RHx7U6SrkEkz08",
            "retry.attempt1.acquirerAccount": "TestPmmAcquirerAccount",
            cardIssuingBank: "ADYEN TEST BANK",
            "retry.attempt1.acquirer": "TestPmmAcquirer",
            authorisedAmountValue: "1000",
            issuerCountry: "NL",
            cvcResult: "1 Matches",
            "retry.attempt1.responseCode": "Approved",
            "fraudCheck-1-PaymentDetailRefCheck": "0",
            "retry.attempt1.shopperInteraction": "Ecommerce",
            cardPaymentMethod: "visa",
            acquirerCode: "TestPmmAcquirer",
          },
          amount: {
            currency: "EUR",
            value: 1000,
          },
          eventCode: "AUTHORISATION",
          eventDate: "2023-02-12T21:45:20+01:00",
          merchantAccountCode: "RochusOffermanECOM",
          merchantReference: "b78ea8cc-b86b-431f-9605-12437f052332",
          operations: ["CANCEL", "CAPTURE", "REFUND"],
          paymentMethod: "visa",
          pspReference: "FNTM8N3MK8NKGK82",
          reason: "074723:1111:03/2030",
          success: "true",
        },
        merchantreference: "68b4f2dd-d771-4f59-872a-e0d5d1bf371d",
        shopperreference:"",
      },
      {
        id: 20,
        pspreference: "VTCQ4VGR8VTFWR82",
        eventcode: "REPORT_AVAILABLE",
        timestamp: "2023-02-12T17:43:37.632+00:00",
        merchantaccount: "BalancePlatform",
        notification: [
          {
            additionalData: {
              "fraudCheck-25-CVCAuthResultCheck": "0",
              avsResult: "5 No AVS data provided",
              cardSummary: "0000",
              "retry.attempt1.avsResultRaw": "5",
              networkTxReference: "737315376215474",
              refusalReasonRaw: "AUTHORISED",
            },
            amount: {
              currency: "EUR",
              value: 1000,
            },
            eventCode: "REPORT_AVAILABLE",
            eventDate: "2023-02-12T18:45:06+01:00",
            merchantAccountCode: "RochusOffermanECOM",
            merchantReference: "4d32c17a-7458-45d3-b015-e67a1eb652d3",
            operations: ["CANCEL", "CAPTURE", "REFUND"],
            paymentMethod: "visa",
            pspReference: "VTCQ4VGR8VTFWR82",
            reason: "004910:0000:03/2030",
            success: "true",
          },
        ],
        merchantreference: "68b4f2dd-d771-4f59-872a-e0d5d1bf371d",
        shopperreference:"",
      },
      {
        id: 19,
        pspreference: "M77G77JB2TGLNK82",
        eventcode: "RECURRING_CONTRACT",
        timestamp: "2023-02-10T10:40:31.366+00:00",
        merchantaccount: "DemoStore",
        notification: [
          {
            additionalData: {
              "fraudCheck-25-CVCAuthResultCheck": "0",
              avsResult: "5 No AVS data provided",
              cardSummary: "0000",
              "retry.attempt1.avsResultRaw": "5",
              networkTxReference: "737315376215474",
              refusalReasonRaw: "AUTHORISED",
            },
            amount: {
              currency: "EUR",
              value: 1000,
            },
            eventCode: "RECURRING_CONTRACT",
            eventDate: "2023-02-12T18:45:06+01:00",
            merchantAccountCode: "RochusOffermanECOM",
            merchantReference: "4d32c17a-7458-45d3-b015-e67a1eb652d3",
            operations: ["CANCEL", "CAPTURE", "REFUND"],
            paymentMethod: "visa",
            pspReference: "M77G77JB2TGLNK82",
            reason: "004910:0000:03/2030",
            success: "true",
          },
        ],
        merchantreference: "68b4f2dd-d771-4f59-872a-e0d5d1bf371d",
        shopperreference:"",
      },
      {
        id: 18,
        pspreference: "M77G77JB2TGLNK82",
        eventcode: "AUTHORISATION",
        timestamp: "2023-02-10T10:40:31.366+00:00",
        merchantaccount: "BalancePlatform",
        notification: [
          {
            additionalData: {
              "fraudCheck-25-CVCAuthResultCheck": "0",
              avsResult: "5 No AVS data provided",
              cardSummary: "0000",
              "retry.attempt1.avsResultRaw": "5",
              networkTxReference: "737315376215474",
              refusalReasonRaw: "AUTHORISED",
            },
            amount: {
              currency: "EUR",
              value: 1000,
            },
            eventCode: "AUTHORISATION",
            eventDate: "2023-02-12T18:45:06+01:00",
            merchantAccountCode: "RochusOffermanECOM",
            merchantReference: "4d32c17a-7458-45d3-b015-e67a1eb652d3",
            operations: ["CANCEL", "CAPTURE", "REFUND"],
            paymentMethod: "visa",
            pspReference: "M77G77JB2TGLNK82",
            reason: "004910:0000:03/2030",
            success: "true",
          },
        ],
        merchantreference: "68b4f2dd-d771-4f59-872a-e0d5d1bf371d",
        shopperreference:"",
      },
      {
        id: 17,
        pspreference: "M77G77JB2TGLNK82",
        eventcode: "RECURRING_CONTRACT",
        timestamp: "2023-02-10T10:40:31.366+00:00",
        merchantaccount: "DemoStore",
        notification: [
          {
            additionalData: {
              "fraudCheck-25-CVCAuthResultCheck": "0",
              avsResult: "5 No AVS data provided",
              cardSummary: "0000",
              "retry.attempt1.avsResultRaw": "5",
              networkTxReference: "737315376215474",
              refusalReasonRaw: "AUTHORISED",
            },
            amount: {
              currency: "EUR",
              value: 1000,
            },
            eventCode: "RECURRING_CONTRACT",
            eventDate: "2023-02-12T18:45:06+01:00",
            merchantAccountCode: "RochusOffermanECOM",
            merchantReference: "4d32c17a-7458-45d3-b015-e67a1eb652d3",
            operations: ["CANCEL", "CAPTURE", "REFUND"],
            paymentMethod: "visa",
            pspReference: "M77G77JB2TGLNK82",
            reason: "004910:0000:03/2030",
            success: "true",
          },
        ],
        merchantreference: "68b4f2dd-d771-4f59-872a-e0d5d1bf371d",
        shopperreference:"",
      },
      {
        id: 16,
        pspreference: "M77G77JB2TGLNK82",
        eventcode: "AUTHORISATION",
        timestamp: "2023-02-10T10:40:31.366+00:00",
        merchantaccount: "BalancePlatform",
        notification: [
          {
            additionalData: {
              "fraudCheck-25-CVCAuthResultCheck": "0",
              avsResult: "5 No AVS data provided",
              cardSummary: "0000",
              "retry.attempt1.avsResultRaw": "5",
              networkTxReference: "737315376215474",
              refusalReasonRaw: "AUTHORISED",
            },
            amount: {
              currency: "EUR",
              value: 1000,
            },
            eventCode: "AUTHORISATION",
            eventDate: "2023-02-12T18:45:06+01:00",
            merchantAccountCode: "RochusOffermanECOM",
            merchantReference: "4d32c17a-7458-45d3-b015-e67a1eb652d3",
            operations: ["CANCEL", "CAPTURE", "REFUND"],
            paymentMethod: "visa",
            pspReference: "M77G77JB2TGLNK82",
            reason: "004910:0000:03/2030",
            success: "true",
          },
        ],
        merchantreference: "68b4f2dd-d771-4f59-872a-e0d5d1bf371d",
        shopperreference:"",
      },
      {
        id: 15,
        pspreference: "M77G77JB2TGLNK82",
        eventcode: "RECURRING_CONTRACT",
        timestamp: "2023-02-10T10:40:31.366+00:00",
        merchantaccount: "DemoStore",
        notification: [
          {
            additionalData: {
              "fraudCheck-25-CVCAuthResultCheck": "0",
              avsResult: "5 No AVS data provided",
              cardSummary: "0000",
              "retry.attempt1.avsResultRaw": "5",
              networkTxReference: "737315376215474",
              refusalReasonRaw: "AUTHORISED",
            },
            amount: {
              currency: "EUR",
              value: 1000,
            },
            eventCode: "RECURRING_CONTRACT",
            eventDate: "2023-02-12T18:45:06+01:00",
            merchantAccountCode: "RochusOffermanECOM",
            merchantReference: "4d32c17a-7458-45d3-b015-e67a1eb652d3",
            operations: ["CANCEL", "CAPTURE", "REFUND"],
            paymentMethod: "visa",
            pspReference: "M77G77JB2TGLNK82",
            reason: "004910:0000:03/2030",
            success: "true",
          },
        ],
        merchantreference: "68b4f2dd-d771-4f59-872a-e0d5d1bf371d",
        shopperreference:"",
      },
      {
        id: 14,
        pspreference: "M77G77JB2TGLNK82",
        eventcode: "AUTHORISATION",
        timestamp: "2023-02-10T10:40:31.366+00:00",
        merchantaccount: "BalancePlatform",
        notification: [
          {
            additionalData: {
              "fraudCheck-25-CVCAuthResultCheck": "0",
              avsResult: "5 No AVS data provided",
              cardSummary: "0000",
              "retry.attempt1.avsResultRaw": "5",
              networkTxReference: "737315376215474",
              refusalReasonRaw: "AUTHORISED",
            },
            amount: {
              currency: "EUR",
              value: 1000,
            },
            eventCode: "AUTHORISATION",
            eventDate: "2023-02-12T18:45:06+01:00",
            merchantAccountCode: "RochusOffermanECOM",
            merchantReference: "4d32c17a-7458-45d3-b015-e67a1eb652d3",
            operations: ["CANCEL", "CAPTURE", "REFUND"],
            paymentMethod: "visa",
            pspReference: "M77G77JB2TGLNK82",
            reason: "004910:0000:03/2030",
            success: "true",
          },
        ],
        merchantreference: "68b4f2dd-d771-4f59-872a-e0d5d1bf371d",
        shopperreference:"",
      },
      {
        id: 13,
        pspreference: "M77G77JB2TGLNK82",
        eventcode: "RECURRING_CONTRACT",
        timestamp: "2023-02-10T10:40:31.366+00:00",
        merchantaccount: "DemoStore",
        notification: [
          {
            additionalData: {
              "fraudCheck-25-CVCAuthResultCheck": "0",
              avsResult: "5 No AVS data provided",
              cardSummary: "0000",
              "retry.attempt1.avsResultRaw": "5",
              networkTxReference: "737315376215474",
              refusalReasonRaw: "AUTHORISED",
            },
            amount: {
              currency: "EUR",
              value: 1000,
            },
            eventCode: "RECURRING_CONTRACT",
            eventDate: "2023-02-12T18:45:06+01:00",
            merchantAccountCode: "RochusOffermanECOM",
            merchantReference: "4d32c17a-7458-45d3-b015-e67a1eb652d3",
            operations: ["CANCEL", "CAPTURE", "REFUND"],
            paymentMethod: "visa",
            pspReference: "M77G77JB2TGLNK82",
            reason: "004910:0000:03/2030",
            success: "true",
          },
        ],
        merchantreference: "68b4f2dd-d771-4f59-872a-e0d5d1bf371d",
        shopperreference:"",
      },
      {
        id: 12,
        pspreference: "M77G77JB2TGLNK82",
        eventcode: "AUTHORISATION",
        timestamp: "2023-02-10T10:40:31.366+00:00",
        merchantaccount: "BalancePlatform",
        notification: [
          {
            additionalData: {
              "fraudCheck-25-CVCAuthResultCheck": "0",
              avsResult: "5 No AVS data provided",
              cardSummary: "0000",
              "retry.attempt1.avsResultRaw": "5",
              networkTxReference: "737315376215474",
              refusalReasonRaw: "AUTHORISED",
            },
            amount: {
              currency: "EUR",
              value: 1000,
            },
            eventCode: "AUTHORISATION",
            eventDate: "2023-02-12T18:45:06+01:00",
            merchantAccountCode: "RochusOffermanECOM",
            merchantReference: "4d32c17a-7458-45d3-b015-e67a1eb652d3",
            operations: ["CANCEL", "CAPTURE", "REFUND"],
            paymentMethod: "visa",
            pspReference: "M77G77JB2TGLNK82",
            reason: "004910:0000:03/2030",
            success: "true",
          },
        ],
        merchantreference: "68b4f2dd-d771-4f59-872a-e0d5d1bf371d",
        shopperreference:"",
      },
      {
        id: 11,
        pspreference: "M77G77JB2TGLNK82",
        eventcode: "RECURRING_CONTRACT",
        timestamp: "2023-02-10T10:40:31.366+00:00",
        merchantaccount: "BalancePlatform",
        notification: [
          {
            additionalData: {
              "fraudCheck-25-CVCAuthResultCheck": "0",
              avsResult: "5 No AVS data provided",
              cardSummary: "0000",
              "retry.attempt1.avsResultRaw": "5",
              networkTxReference: "737315376215474",
              refusalReasonRaw: "AUTHORISED",
            },
            amount: {
              currency: "EUR",
              value: 1000,
            },
            eventCode: "RECURRING_CONTRACT",
            eventDate: "2023-02-12T18:45:06+01:00",
            merchantAccountCode: "RochusOffermanECOM",
            merchantReference: "4d32c17a-7458-45d3-b015-e67a1eb652d3",
            operations: ["CANCEL", "CAPTURE", "REFUND"],
            paymentMethod: "visa",
            pspReference: "M77G77JB2TGLNK82",
            reason: "004910:0000:03/2030",
            success: "true",
          },
        ],
        merchantreference: "68b4f2dd-d771-4f59-872a-e0d5d1bf371d",
        shopperreference:"",
      },
      {
        id: 10,
        pspreference: "M77G77JB2TGLNK82",
        eventcode: "AUTHORISATION",
        timestamp: "2023-02-10T10:40:31.366+00:00",
        merchantaccount: "BalancePlatform",
        notification: [
          {
            additionalData: {
              "fraudCheck-25-CVCAuthResultCheck": "0",
              avsResult: "5 No AVS data provided",
              cardSummary: "0000",
              "retry.attempt1.avsResultRaw": "5",
              networkTxReference: "737315376215474",
              refusalReasonRaw: "AUTHORISED",
            },
            amount: {
              currency: "EUR",
              value: 1000,
            },
            eventCode: "AUTHORISATION",
            eventDate: "2023-02-12T18:45:06+01:00",
            merchantAccountCode: "RochusOffermanECOM",
            merchantReference: "4d32c17a-7458-45d3-b015-e67a1eb652d3",
            operations: ["CANCEL", "CAPTURE", "REFUND"],
            paymentMethod: "visa",
            pspReference: "M77G77JB2TGLNK82",
            reason: "004910:0000:03/2030",
            success: "true",
          },
        ],
        merchantreference: "68b4f2dd-d771-4f59-872a-e0d5d1bf371d",
        shopperreference:"",
      },
      {
        id: 9,
        pspreference: "M77G77JB2TGLNK82",
        eventcode: "RECURRING_CONTRACT",
        timestamp: "2023-02-10T10:40:31.366+00:00",
        merchantaccount: "BalancePlatform",
        notification: [
          {
            additionalData: {
              "fraudCheck-25-CVCAuthResultCheck": "0",
              avsResult: "5 No AVS data provided",
              cardSummary: "0000",
              "retry.attempt1.avsResultRaw": "5",
              networkTxReference: "737315376215474",
              refusalReasonRaw: "AUTHORISED",
            },
            amount: {
              currency: "EUR",
              value: 1000,
            },
            eventCode: "RECURRING_CONTRACT",
            eventDate: "2023-02-12T18:45:06+01:00",
            merchantAccountCode: "RochusOffermanECOM",
            merchantReference: "4d32c17a-7458-45d3-b015-e67a1eb652d3",
            operations: ["CANCEL", "CAPTURE", "REFUND"],
            paymentMethod: "visa",
            pspReference: "M77G77JB2TGLNK82",
            reason: "004910:0000:03/2030",
            success: "true",
          },
        ],
        merchantreference: "68b4f2dd-d771-4f59-872a-e0d5d1bf371d",
        shopperreference:"",
      },
      {
        id: 8,
        pspreference: "M77G77JB2TGLNK82",
        eventcode: "AUTHORISATION",
        timestamp: "2023-02-10T10:40:31.366+00:00",
        merchantaccount: "BalancePlatform",
        notification: [
          {
            additionalData: {
              "fraudCheck-25-CVCAuthResultCheck": "0",
              avsResult: "5 No AVS data provided",
              cardSummary: "0000",
              "retry.attempt1.avsResultRaw": "5",
              networkTxReference: "737315376215474",
              refusalReasonRaw: "AUTHORISED",
            },
            amount: {
              currency: "EUR",
              value: 1000,
            },
            eventCode: "AUTHORISATION",
            eventDate: "2023-02-12T18:45:06+01:00",
            merchantAccountCode: "RochusOffermanECOM",
            merchantReference: "4d32c17a-7458-45d3-b015-e67a1eb652d3",
            operations: ["CANCEL", "CAPTURE", "REFUND"],
            paymentMethod: "visa",
            pspReference: "M77G77JB2TGLNK82",
            reason: "004910:0000:03/2030",
            success: "true",
          },
        ],
        merchantreference: "68b4f2dd-d771-4f59-872a-e0d5d1bf371d",
        shopperreference:"",
      },
      {
        id: 7,
        pspreference: "M77G77JB2TGLNK82",
        eventcode: "RECURRING_CONTRACT",
        timestamp: "2023-02-10T10:40:31.366+00:00",
        merchantaccount: "",
        notification: [
          {
            additionalData: {
              "fraudCheck-25-CVCAuthResultCheck": "0",
              avsResult: "5 No AVS data provided",
              cardSummary: "0000",
              "retry.attempt1.avsResultRaw": "5",
              networkTxReference: "737315376215474",
              refusalReasonRaw: "AUTHORISED",
            },
            amount: {
              currency: "EUR",
              value: 1000,
            },
            eventCode: "RECURRING_CONTRACT",
            eventDate: "2023-02-12T18:45:06+01:00",
            merchantAccountCode: "RochusOffermanECOM",
            merchantReference: "4d32c17a-7458-45d3-b015-e67a1eb652d3",
            operations: ["CANCEL", "CAPTURE", "REFUND"],
            paymentMethod: "visa",
            pspReference: "M77G77JB2TGLNK82",
            reason: "004910:0000:03/2030",
            success: "true",
          },
        ],
        merchantreference: "68b4f2dd-d771-4f59-872a-e0d5d1bf371d",
        shopperreference:"",
      },
      {
        id: 6,
        pspreference: "M77G77JB2TGLNK82",
        eventcode: "AUTHORISATION",
        timestamp: "2023-02-10T10:40:31.366+00:00",
        merchantaccount: "",
        notification: [
          {
            additionalData: {
              "fraudCheck-25-CVCAuthResultCheck": "0",
              avsResult: "5 No AVS data provided",
              cardSummary: "0000",
              "retry.attempt1.avsResultRaw": "5",
              networkTxReference: "737315376215474",
              refusalReasonRaw: "AUTHORISED",
            },
            amount: {
              currency: "EUR",
              value: 1000,
            },
            eventCode: "AUTHORISATION",
            eventDate: "2023-02-12T18:45:06+01:00",
            merchantAccountCode: "RochusOffermanECOM",
            merchantReference: "4d32c17a-7458-45d3-b015-e67a1eb652d3",
            operations: ["CANCEL", "CAPTURE", "REFUND"],
            paymentMethod: "visa",
            pspReference: "M77G77JB2TGLNK82",
            reason: "004910:0000:03/2030",
            success: "true",
          },
        ],
        merchantreference: "68b4f2dd-d771-4f59-872a-e0d5d1bf371d",
        shopperreference:"",
      },
      {
        id: 5,
        pspreference: "M77G77JB2TGLNK82",
        eventcode: "RECURRING_CONTRACT",
        timestamp: "2023-02-10T10:40:31.366+00:00",
        merchantaccount: "",
        notification: [
          {
            additionalData: {
              "fraudCheck-25-CVCAuthResultCheck": "0",
              avsResult: "5 No AVS data provided",
              cardSummary: "0000",
              "retry.attempt1.avsResultRaw": "5",
              networkTxReference: "737315376215474",
              refusalReasonRaw: "AUTHORISED",
            },
            amount: {
              currency: "EUR",
              value: 1000,
            },
            eventCode: "RECURRING_CONTRACT",
            eventDate: "2023-02-12T18:45:06+01:00",
            merchantAccountCode: "RochusOffermanECOM",
            merchantReference: "4d32c17a-7458-45d3-b015-e67a1eb652d3",
            operations: ["CANCEL", "CAPTURE", "REFUND"],
            paymentMethod: "visa",
            pspReference: "M77G77JB2TGLNK82",
            reason: "004910:0000:03/2030",
            success: "true",
          },
        ],
        merchantreference: "68b4f2dd-d771-4f59-872a-e0d5d1bf371d",
        shopperreference:"",
      },
      {
        id: 4,
        pspreference: "M77G77JB2TGLNK82",
        eventcode: "AUTHORISATION",
        timestamp: "2023-02-10T10:40:31.366+00:00",
        merchantaccount: "",
        notification: [
          {
            additionalData: {
              "fraudCheck-25-CVCAuthResultCheck": "0",
              avsResult: "5 No AVS data provided",
              cardSummary: "0000",
              "retry.attempt1.avsResultRaw": "5",
              networkTxReference: "737315376215474",
              refusalReasonRaw: "AUTHORISED",
            },
            amount: {
              currency: "EUR",
              value: 1000,
            },
            eventCode: "AUTHORISATION",
            eventDate: "2023-02-12T18:45:06+01:00",
            merchantAccountCode: "RochusOffermanECOM",
            merchantReference: "4d32c17a-7458-45d3-b015-e67a1eb652d3",
            operations: ["CANCEL", "CAPTURE", "REFUND"],
            paymentMethod: "visa",
            pspReference: "M77G77JB2TGLNK82",
            reason: "004910:0000:03/2030",
            success: "true",
          },
        ],
        merchantreference: "68b4f2dd-d771-4f59-872a-e0d5d1bf371d",
        shopperreference:"",
      },
      {
        id: 3,
        pspreference: "M77G77JB2TGLNK82",
        eventcode: "RECURRING_CONTRACT",
        timestamp: "2023-02-10T10:40:31.366+00:00",
        merchantaccount: "",
        notification: [
          {
            additionalData: {
              "fraudCheck-25-CVCAuthResultCheck": "0",
              avsResult: "5 No AVS data provided",
              cardSummary: "0000",
              "retry.attempt1.avsResultRaw": "5",
              networkTxReference: "737315376215474",
              refusalReasonRaw: "AUTHORISED",
            },
            amount: {
              currency: "EUR",
              value: 1000,
            },
            eventCode: "RECURRING_CONTRACT",
            eventDate: "2023-02-12T18:45:06+01:00",
            merchantAccountCode: "RochusOffermanECOM",
            merchantReference: "4d32c17a-7458-45d3-b015-e67a1eb652d3",
            operations: ["CANCEL", "CAPTURE", "REFUND"],
            paymentMethod: "visa",
            pspReference: "M77G77JB2TGLNK82",
            reason: "004910:0000:03/2030",
            success: "true",
          },
        ],
        merchantreference: "68b4f2dd-d771-4f59-872a-e0d5d1bf371d",
        shopperreference:"",
      },
      {
        id: 2,
        pspreference: "M77G77JB2TGLNK82",
        eventcode: "AUTHORISATION",
        timestamp: "2023-02-10T10:40:31.366+00:00",
        merchantaccount: "",
        notification: [
          {
            additionalData: {
              "fraudCheck-25-CVCAuthResultCheck": "0",
              avsResult: "5 No AVS data provided",
              cardSummary: "0000",
              "retry.attempt1.avsResultRaw": "5",
              networkTxReference: "737315376215474",
              refusalReasonRaw: "AUTHORISED",
            },
            amount: {
              currency: "EUR",
              value: 1000,
            },
            eventCode: "AUTHORISATION",
            eventDate: "2023-02-12T18:45:06+01:00",
            merchantAccountCode: "RochusOffermanECOM",
            merchantReference: "4d32c17a-7458-45d3-b015-e67a1eb652d3",
            operations: ["CANCEL", "CAPTURE", "REFUND"],
            paymentMethod: "visa",
            pspReference: "M77G77JB2TGLNK82",
            reason: "004910:0000:03/2030",
            success: "true",
          },
        ],
        merchantreference: "68b4f2dd-d771-4f59-872a-e0d5d1bf371d",
        shopperreference:"",
      },
      {
        id: 1,
        pspreference: "M77G77JB2TGLNK82",
        eventcode: "RECURRING_CONTRACT",
        timestamp: "2023-02-10T10:40:31.366+00:00",
        merchantaccount: "",
        notification: [
          {
            additionalData: {
              "fraudCheck-25-CVCAuthResultCheck": "0",
              avsResult: "5 No AVS data provided",
              cardSummary: "0000",
              "retry.attempt1.avsResultRaw": "5",
              networkTxReference: "737315376215474",
              refusalReasonRaw: "AUTHORISED",
            },
            amount: {
              currency: "EUR",
              value: 1000,
            },
            eventCode: "RECURRING_CONTRACT",
            eventDate: "2023-02-12T18:45:06+01:00",
            merchantAccountCode: "RochusOffermanECOM",
            merchantReference: "4d32c17a-7458-45d3-b015-e67a1eb652d3",
            operations: ["CANCEL", "CAPTURE", "REFUND"],
            paymentMethod: "visa",
            pspReference: "M77G77JB2TGLNK82",
            reason: "004910:0000:03/2030",
            success: "true",
          },
        ],
        merchantreference: "68b4f2dd-d771-4f59-872a-e0d5d1bf371d",
        shopperreference:"",
      },
    ],
    balanceNotificationItem: "",
    balanceNotifications: [
      {
        id: 1,
        timestamp: "",
        balancenotification: "",
        type: "",
        balanceplatform: "",
        accountholderid: "",
        balanceaccountid: "",
        legalentityid: "",
        paymentinstrumentid: "",
        transferid: "",
        psppaymentreference: "",
        transactionid: "",
        reference: "",
      },
    ],
    balanceNotificationsExample: [
      {
        id: 1,
        timestamp: "2023-02-31T01:45:07.150+00:00",
        balancenotification: {
          data: {
            balancePlatform: "ROOFTOWN",
            accountHolder: {
              contactDetails: {},
              description: "TEST-BCL-ROOFTOWN-AH-ORGANISATION-1",
              legalEntityId: "LE322KH223222J5HHL9L3DM7X",
              reference: "TESTWEBHOOK",
              capabilities: {
                receiveFromPlatformPayments: {
                  enabled: "true",
                  requested: "true",
                  allowed: "true",
                  verificationStatus: "valid",
                },
                receiveFromBalanceAccount: {
                  enabled: "true",
                  requested: "true",
                  allowed: "true",
                  verificationStatus: "valid",
                },
                sendToBalanceAccount: {
                  enabled: "true",
                  requested: "true",
                  allowed: "true",
                  verificationStatus: "valid",
                },
                receivePayments: {
                  enabled: "true",
                  requested: "true",
                  allowed: "true",
                  verificationStatus: "valid",
                },
              },
              id: "AH32272223222H5HV3KD68H7J",
              status: "Active",
            },
          },
          environment: "test",
          type: "balancePlatform.accountHolder.created",
        },
        type: "balancePlatform.accountHolder.created",
        balanceplatform: "RAVI",
        accountholderid:"account",
        balanceaccountid:"balance",
        legalentityid:"legal",
        paymentinstrumentid:"int",
        transferid:"transfer",
        psppaymentreference:"psp",
        transactionid:"transc",
        reference:"ref",
      },
      {
        id: 2,
        timestamp: "2023-02-29T12:45:07.150+00:00",
        balancenotification: {
          data: {
            balancePlatform: "ROOFTOWN",
            accountHolder: {
              description: "TEST-BCL-ROOFTOWN-AH-ORGANISATION-1",
              legalEntityId: "LE322JV223222Q5HWB97B46DB",
              reference: "e57cd07de6954f05ad53272d0ebc7987",
              capabilities: {
                receiveFromBalanceAccount: {
                  enabled: "true",
                  requested: "true",
                  allowed: "false",
                  verificationStatus: "pending",
                },
              },
              id: "AH3227C223222H5HWB9FC9CML",
              status: "Active",
            },
          },
          environment: "test",
          type: "balancePlatform.accountHolder.updated",
        },
        // type: "balancePlatform.accountHolder.updated",
        type: "balancePlatform.accountHolder.created",
        balanceplatform: "ROOFTOWN",
        accountholderid:"",
        balanceaccountid:"",
        legalentityid:"",
        paymentinstrumentid:"",
        transferid:"",
        psppaymentreference:"",
        transactionid:"",
        reference:"",
      },
      {
        id: 3,
        timestamp: "2023-02-28T20:45:07.150+00:00",
        balancenotification: {
          data: {
            balancePlatform: "ROOFTOWN",
            balanceAccount: {
              accountHolderId: "AH32272223222H5HWB4Z25QBB",
              defaultCurrencyCode: "EUR",
              description: "TEST BalanceAccount",
              timeZone: "Europe/Amsterdam",
              id: "BA3227C223222H5HWB85Z9CKV",
              status: "Active",
            },
          },
          environment: "test",
          type: "balancePlatform.balanceAccount.created",
        },
        type: "balancePlatform.balanceAccount.created",
        balanceplatform: "ROOFTOWN",
        accountholderid:"",
        balanceaccountid:"",
        legalentityid:"",
        paymentinstrumentid:"",
        transferid:"",
        psppaymentreference:"",
        transactionid:"",
        reference:"",
      },
      {
        id: 4,
        timestamp: "2023-02-26T03:45:07.150+00:00",
        balancenotification: {
          data: {
            balancePlatform: "ROOFTOWN",
            balanceAccount: {
              accountHolderId: "AH3227C223222H5HWB9FC9CML",
              defaultCurrencyCode: "EUR",
              description: "PATCH BalanceAccount",
              timeZone: "Europe/Amsterdam",
              id: "BA32272223222H5HWB9FM5QL6",
              status: "Active",
            },
          },
          environment: "test",
          type: "balancePlatform.balanceAccount.updated",
        },
        type: "balancePlatform.balanceAccount.updated",
        balanceplatform: "ROOFTOWN",
        accountholderid:"",
        balanceaccountid:"",
        legalentityid:"",
        paymentinstrumentid:"",
        transferid:"",
        psppaymentreference:"",
        transactionid:"",
        reference:"",
      },
      {
        id: 5,
        timestamp: "2023-02-26T13:45:07.150+00:00",
        balancenotification: {
          data: {
            balancePlatform: "ROOFTOWN",
            accountId: "BA32272223222H5HWB9FM5QL6",
            sweep: {
              id: "SWPC4227C223222H5HWP88V59K4X2D",
              schedule: {
                type: "balance",
              },
              status: "active",
              sweepAmount: {
                currency: "EUR",
                value: 4000,
              },
              triggerAmount: {
                currency: "EUR",
                value: 3500,
              },
              type: "pull",
              counterparty: {
                merchantAccount: "RochusOffermanPayouts",
              },
              currency: "EUR",
            },
          },
          environment: "test",
          type: "balancePlatform.balanceAccountSweep.created",
        },
        type: "balancePlatform.balanceAccountSweep.created",
        balanceplatform: "ROOFTOWN",
        accountholderid:"",
        balanceaccountid:"",
        legalentityid:"",
        paymentinstrumentid:"",
        transferid:"",
        psppaymentreference:"",
        transactionid:"",
        reference:"",
      },
      {
        id: 6,
        timestamp: "2023-02-23T22:45:07.150+00:00",
        balancenotification: {
          data: {
            balancePlatform: "ROOFTOWN",
            accountId: "BA3227C223222D5HCNK7Z99BG",
            sweep: {
              id: "SWPC42272223222G5HLKS685492PKZ",
              schedule: {
                type: "balance",
              },
              status: "active",
              sweepAmount: {
                currency: "EUR",
                value: 4000,
              },
              triggerAmount: {
                currency: "EUR",
                value: 3500,
              },
              type: "pull",
              counterparty: {
                merchantAccount: "RochusOffermanPayouts",
              },
              currency: "EUR",
            },
          },
          environment: "test",
          type: "balancePlatform.balanceAccountSweep.updated",
        },
        type: "balancePlatform.balanceAccountSweep.updated",
        balanceplatform: "ROOFTOWN",
        accountholderid:"",
        balanceaccountid:"",
        legalentityid:"",
        paymentinstrumentid:"",
        transferid:"",
        psppaymentreference:"",
        transactionid:"",
        reference:"",
      },
      {
        id: 7,
        timestamp: "2023-02-22T17:45:07.150+00:00",
        balancenotification: {
          data: {
            balancePlatform: "ROOFTOWN",
            paymentInstrument: {
              balanceAccountId: "BA3227C223222D5HCNK7Z99BG",
              description: "Test",
              issuingCountryCode: "NL",
              reference: "Test",
              status: "Active",
              type: "card",
              card: {
                cardholderName: "nMnoDvmxbMIz7XnUg7W8V$x0",
                formFactor: "virtual",
                bin: "555544",
                expiration: {
                  month: "05",
                  year: "2026",
                },
                lastFour: "3861",
              },
              id: "PI3227C223222H5HWP7J528TS",
            },
          },
          environment: "test",
          type: "balancePlatform.paymentInstrument.created",
        },
        type: "balancePlatform.paymentInstrument.created",
        balanceplatform: "ROOFTOWN",
        accountholderid:"",
        balanceaccountid:"",
        legalentityid:"",
        paymentinstrumentid:"",
        transferid:"",
        psppaymentreference:"",
        transactionid:"",
        reference:"",
      },
      {
        id: 8,
        timestamp: "2023-02-22T18:45:07.150+00:00",
        balancenotification: {
          data: {
            balancePlatform: "ROOFTOWN",
            paymentInstrument: {
              balanceAccountId: "BA3227C223222C5GQJ6BLGPJ3",
              description: "RJP Offerman - Second card",
              issuingCountryCode: "NL",
              status: "Suspended",
              type: "card",
              card: {
                cardholderName: "nMnoDvmxbMIz7XnUg7W8V$x0",
                formFactor: "virtual",
                bin: "555544",
                expiration: {
                  month: "10",
                  year: "2025",
                },
                lastFour: "4422",
              },
              id: "PI3227C223222C5GQJFTLGQBV",
            },
          },
          environment: "test",
          type: "balancePlatform.paymentInstrument.updated",
        },
        type: "balancePlatform.paymentInstrument.updated",
        balanceplatform: "ROOFTOWN",
        accountholderid:"",
        balanceaccountid:"",
        legalentityid:"",
        paymentinstrumentid:"",
        transferid:"",
        psppaymentreference:"",
        transactionid:"",
        reference:"",
      },
      {
        id: 9,
        timestamp: "2023-02-20T23:45:07.150+00:00",
        balancenotification: {
          data: {
            balancePlatform: "ROOFTOWN",
            creationDate: "2023-05-17T22:13:53+02:00",
            id: "3JY1YE5YXTFJX62A",
            amount: {
              currency: "EUR",
              value: 9,
            },
            balanceAccountId: "BA3227C223222B5G4SFRS3CKT",
            category: "internal",
            reference: "Split reference not provided",
            accountHolder: {
              description: "ROOFTOWN Account Holder",
              id: "AH32272223222B5G4SFRSGFLQ",
            },
            balanceAccount: {
              description: "ROOFTOWN Liable Balance Account",
              id: "BA3227C223222B5G4SFRS3CKT",
            },
            direction: "outgoing",
            reason: "approved",
            status: "received",
            balances: [
              {
                currency: "EUR",
                received: -9,
              },
            ],
            events: [
              {
                bookingDate: "2023-05-17T22:14:17+02:00",
                id: "EVJN4227222422295HVBZBC7LC69WM",
                mutations: [
                  {
                    currency: "EUR",
                    received: -9,
                  },
                ],
                status: "received",
                type: "accounting",
              },
            ],
            modificationMerchantReference:
              "Transaction fees from batch 22 for account RochusOffermanAFP_BP_PartnerModel",
            modificationPspReference: "F7SRXH9GRPRNTT82",
            sequenceNumber: 1,
            type: "fee",
          },
          environment: "test",
          type: "balancePlatform.transfer.created",
        },
        type: "balancePlatform.transfer.created",
        balanceplatform: "ROOFTOWN",
        accountholderid:"",
        balanceaccountid:"",
        legalentityid:"",
        paymentinstrumentid:"",
        transferid:"",
        psppaymentreference:"",
        transactionid:"",
        reference:"",
      },
      {
        id: 10,
        timestamp: "2023-02-11T16:45:07.150+00:00",
        balancenotification: {
          data: {
            balancePlatform: "ROOFTOWN",
            creationDate: "2023-05-17T22:13:53+02:00",
            id: "3JY1YE5YXTFJX62A",
            amount: {
              currency: "EUR",
              value: 9,
            },
            balanceAccountId: "BA3227C223222B5G4SFRS3CKT",
            category: "internal",
            reference: "Split reference not provided",
            accountHolder: {
              description: "ROOFTOWN Account Holder",
              id: "AH32272223222B5G4SFRSGFLQ",
            },
            balanceAccount: {
              description: "ROOFTOWN Liable Balance Account",
              id: "BA3227C223222B5G4SFRS3CKT",
            },
            direction: "outgoing",
            reason: "approved",
            status: "authorised",
            balances: [
              {
                currency: "EUR",
                received: 0,
                reserved: -9,
              },
            ],
            events: [
              {
                bookingDate: "2023-05-17T22:14:17+02:00",
                id: "EVJN4227222422295HVBZBC7LC69WM",
                mutations: [
                  {
                    currency: "EUR",
                    received: -9,
                  },
                ],
                status: "received",
                type: "accounting",
              },
              {
                bookingDate: "2023-05-17T22:14:17+02:00",
                id: "EVJN4227C22422295HVBZBC2PT4JX9",
                mutations: [
                  {
                    currency: "EUR",
                    received: 9,
                    reserved: -9,
                  },
                ],
                status: "authorised",
                type: "accounting",
              },
            ],
            modificationMerchantReference:
              "Transaction fees from batch 22 for account RochusOffermanAFP_BP_PartnerModel",
            modificationPspReference: "F7SRXH9GRPRNTT82",
            sequenceNumber: 2,
            type: "fee",
          },
          environment: "test",
          type: "balancePlatform.transfer.updated",
        },
        type: "balancePlatform.transfer.updated",
        balanceplatform: "ROOFTOWN",
        accountholderid:"",
        balanceaccountid:"",
        legalentityid:"",
        paymentinstrumentid:"",
        transferid:"",
        psppaymentreference:"",
        transactionid:"",
        reference:"",
      },
      {
        id: 11,
        timestamp: "2023-02-04T23:45:07.150+00:00",
        balancenotification: {
          data: {
            balancePlatform: "ROOFTOWN",
            creationDate: "2023-05-17T22:13:53+02:00",
            id: "3JY1YE5YXTFJX62A",
            amount: {
              currency: "EUR",
              value: 9,
            },
            balanceAccountId: "BA3227C223222B5G4SFRS3CKT",
            category: "internal",
            reference: "Split reference not provided",
            accountHolder: {
              description: "ROOFTOWN Account Holder",
              id: "AH32272223222B5G4SFRSGFLQ",
            },
            balanceAccount: {
              description: "ROOFTOWN Liable Balance Account",
              id: "BA3227C223222B5G4SFRS3CKT",
            },
            direction: "outgoing",
            reason: "approved",
            status: "fee",
            balances: [
              {
                balance: -9,
                currency: "EUR",
                received: 0,
                reserved: 0,
              },
            ],
            events: [
              {
                bookingDate: "2023-05-17T22:14:17+02:00",
                id: "EVJN4227222422295HVBZBC7LC69WM",
                mutations: [
                  {
                    currency: "EUR",
                    received: -9,
                  },
                ],
                status: "received",
                type: "accounting",
              },
              {
                bookingDate: "2023-05-17T22:14:17+02:00",
                id: "EVJN4227C22422295HVBZBC2PT4JX9",
                mutations: [
                  {
                    currency: "EUR",
                    received: 9,
                    reserved: -9,
                  },
                ],
                status: "authorised",
                type: "accounting",
              },
              {
                bookingDate: "2023-05-17T22:14:23+02:00",
                id: "EVJN4227222422295HVBZBK7LN6J9W",
                mutations: [
                  {
                    balance: -9,
                    currency: "EUR",
                    received: 0,
                    reserved: 9,
                  },
                ],
                status: "fee",
                transactionId: "3JY1YE5YXTFJX638",
                type: "accounting",
                valueDate: "2023-05-17T22:14:23+02:00",
              },
            ],
            modificationMerchantReference:
              "Transaction fees from batch 22 for account RochusOffermanAFP_BP_PartnerModel",
            modificationPspReference: "F7SRXH9GRPRNTT82",
            sequenceNumber: 3,
            transactionId: "3JY1YE5YXTFJX638",
            type: "fee",
          },
          environment: "test",
          type: "balancePlatform.transfer.updated",
        },
        type: "balancePlatform.transfer.updated",
        balanceplatform: "ROOFTOWN",
        accountholderid:"",
        balanceaccountid:"",
        legalentityid:"",
        paymentinstrumentid:"",
        transferid:"",
        psppaymentreference:"",
        transactionid:"",
        reference:"",
      },
      {
        id: 12,
        timestamp: "2023-02-02T23:45:07.150+00:00",
        balancenotification: {
          data: {
            balancePlatform: "ROOFTOWN",
            creationDate: "2022-12-01T13:19:51+01:00",
            id: "3JERI45X3EIMS233",
            accountHolder: {
              description: "TEST-AH-ISSUING-ROOFTOWN",
              id: "AH32272223222C5GQHMJZ7H5P",
              reference: "Test1",
            },
            amount: {
              currency: "GBP",
              value: 100000,
            },
            balanceAccount: {
              description: " Issuing Balance Account GBP",
              id: "BA3227C223222C5H2RTQ85KCX",
            },
            balanceAccountId: "BA3227C223222C5H2RTQ85KCX",
            category: "platformPayment",
            direction: "incoming",
            reason: "approved",
            reference: "Order-6172355",
            status: "captured",
            balances: [
              {
                balance: 100000,
                currency: "GBP",
                received: 0,
                reserved: 0,
              },
            ],
            events: [
              {
                bookingDate: "2022-12-01T13:25:12+01:00",
                id: "EVJN4227222422265H2SFBV3666FBD",
                mutations: [
                  {
                    currency: "GBP",
                    received: 100000,
                  },
                ],
                status: "received",
                type: "accounting",
              },
              {
                bookingDate: "2022-12-01T13:25:12+01:00",
                id: "EVJN4227222422265H2SFBV3674JNM",
                mutations: [
                  {
                    currency: "GBP",
                    received: -100000,
                    reserved: 100000,
                  },
                ],
                status: "authorised",
                type: "accounting",
              },
              {
                bookingDate: "2023-05-26T13:21:37+02:00",
                id: "EVJN4227C22422295HWJXDC27K4SQG",
                mutations: [
                  {
                    balance: 100000,
                    currency: "GBP",
                    received: 0,
                    reserved: -100000,
                  },
                ],
                status: "captured",
                transactionId: "3JERI45X3EIMZRYA",
                type: "accounting",
                valueDate: "2023-05-26T13:21:37+02:00",
              },
            ],
            modificationPspReference: "CCJGXSSF6VTFWR82",
            paymentMerchantReference: "Book transaction fees to sub-merchants",
            pspPaymentReference: "T8QKP4G7MGNG5S82",
            sequenceNumber: 3,
            transactionId: "3JERI45X3EIMZRYA",
            type: "capture",
          },
          environment: "test",
          type: "balancePlatform.transfer.updated",
        },
        type: "balancePlatform.transfer.updated",
        balanceplatform: "ROOFTOWN",
        accountholderid:"",
        balanceaccountid:"",
        legalentityid:"",
        paymentinstrumentid:"",
        transferid:"",
        psppaymentreference:"",
        transactionid:"",
        reference:"",
      },
    ],
    paymentList: [
      {
        id: 1,
        pspReference: "",
        eventCode: "",
        merchantReference: "",
        shopperReference: "",
        timestamp: "",
        merchantAccount: "",
        paymentMethod: "",
        amount: "",
        currency: "",
        success: "",
        refusalReasonRaw: "",
        networkTxReference: "",
        liabilityShift: "",
        threeDSVersion: "",
        threeDAuthenticated: "",
        threeDAuthenticatedResponse: "",
        threeDOffered: "",
        threeDOfferedResponse: "",
        expiryDate: "",
        cardBin: "",
        cardSummary: "",
        issuerCountry: "",
        fundingSource: "",
        metaData: "",
        iban: "",
        shopperEmail: "",
        shopperInteraction: "",
      },
    ],
    // paymentList: [
    //   {
    //     id: 25,
    //     pspreference: "QXGTSWK4ZGXXGN82",
    //     eventcode: "AUTHORISATION",
    //     merchantreference: "4b063b92-5138-4ec3-8254-aeae98f5a5a1",
    //     shopperreference: "",
    //     timestamp: "2023-03-05T21:56:20.036+00:00",//"2023-05-12T17:45:07.150+00:00"
    //     merchantaccount: "RogOffermanECOM",
    //     paymentmethod: "visa",
    //     amount: "500",
    //     currency: "EUR",
    //     success: "true",
    //     refusalreasonraw: "AUTHORISED",
    //     networktxreference: "441454893511382",
    //     liabilityshift: "false",
    //     threedsversion: "1.0.2",
    //     threedauthenticated: "false",
    //     threedauthenticatedresponse: "N/A",
    //     threedoffered: "true",
    //     threedofferedresponse: "U",
    //     expirydate: "03/2030",
    //     cardbin: "411111",
    //     cardsummary: "1111",
    //     issuercountry: "NL",
    //     fundingsource: "",
    //     metadata: "",
    //     iban: "",
    //     shopperemail: "",
    //     shopperinteraction: "",
    //   },
    //   {
    //     id: 24,
    //     pspreference: "J4SF9N38QGNG5S82",
    //     eventcode: "AUTHORISATION",
    //     merchantreference: "168d040f-2914-4439-b726-c1275b43b33d",
    //     shopperreference: "",
    //     timestamp: "2023-03-05T21:55:27.748+00:00",
    //     merchantaccount: "RochusOffermanECOM",
    //     paymentmethod: "visa",
    //     amount: "600",
    //     currency: "EUR",
    //     success: "true",
    //     refusalreasonraw: "AUTHORISED",
    //     networktxreference: "247846617765473",
    //     liabilityshift: "true",
    //     threedsversion: "2.2.0",
    //     threedauthenticated: "true",
    //     threedauthenticatedresponse: "Y",
    //     threedoffered: "true",
    //     threedofferedresponse: "C",
    //     expirydate: "03/2030",
    //     cardbin: "491761",
    //     cardsummary: "0000",
    //     issuercountry: "PL",
    //     fundingsource: "CREDIT",
    //     metadata: "",
    //     iban: "",
    //     shopperemail: "",
    //     shopperinteraction: "",
    //   },
    //   {
    //     id: 23,
    //     pspreference: "HB87VVK4ZGXXGN82",
    //     eventcode: "AUTHORISATION",
    //     merchantreference: "9bb39ecd-3bb4-4c9b-a68f-6c61f1d017f3",
    //     shopperreference: "",
    //     timestamp: "2023-03-05T21:54:23.290+00:00",
    //     merchantaccount: "RochusOffermanECOM",
    //     paymentmethod: "visa",
    //     amount: "1000",
    //     currency: "EUR",
    //     success: "true",
    //     refusalreasonraw: "AUTHORISED",
    //     networktxreference: "279001928811599",
    //     liabilityshift: "false",
    //     threedsversion: "1.0.2",
    //     threedauthenticated: "false",
    //     threedauthenticatedresponse: "N/A",
    //     threedoffered: "true",
    //     threedofferedresponse: "U",
    //     expirydate: "03/2030",
    //     cardbin: "411111",
    //     cardsummary: "1111",
    //     issuercountry: "NL",
    //     fundingsource: "",
    //     metadata: "",
    //     iban: "",
    //     shopperemail: "",
    //     shopperinteraction: "",
    //   },
    //   {
    //     id: 22,
    //     pspreference: "R2TV55GPW5PFWR82",
    //     eventcode: "AUTHORISATION",
    //     merchantreference: "09afc123-e5ee-40a7-a029-d04543886a7c",
    //     shopperreference: "",
    //     timestamp: "2023-03-02T14:52:31.483+00:00",
    //     merchantaccount: "RochusOffermanECOM",
    //     paymentmethod: "eps",
    //     amount: "1000",
    //     currency: "EUR",
    //     success: "false",
    //     refusalreasonraw: "",
    //     networktxreference: "",
    //     liabilityshift: "",
    //     threedsversion: "",
    //     threedauthenticated: "",
    //     threedauthenticatedresponse: "",
    //     threedoffered: "",
    //     threedofferedresponse: "",
    //     expirydate: "",
    //     cardbin: "",
    //     cardsummary: "",
    //     issuercountry: "",
    //     fundingsource: "",
    //     metadata: "",
    //     iban: "",
    //     shopperemail: "",
    //     shopperinteraction: "",
    //   },
    //   {
    //     id: 21,
    //     pspreference: "R5L5CW654CLZNN82",
    //     eventcode: "AUTHORISATION",
    //     merchantreference: "550d12a4-ca12-46c9-b12b-40d9244498e2",
    //     shopperreference: "",
    //     timestamp: "2023-03-02T14:52:31.436+00:00",
    //     merchantaccount: "RochusOffermanECOM",
    //     paymentmethod: "eps",
    //     amount: "1000",
    //     currency: "EUR",
    //     success: "false",
    //     refusalreasonraw: "",
    //     networktxreference: "",
    //     liabilityshift: "",
    //     threedsversion: "",
    //     threedauthenticated: "",
    //     threedauthenticatedresponse: "",
    //     threedoffered: "",
    //     threedofferedresponse: "",
    //     expirydate: "",
    //     cardbin: "",
    //     cardsummary: "",
    //     issuercountry: "",
    //     fundingsource: "",
    //     metadata: "",
    //     iban: "",
    //     shopperemail: "",
    //     shopperinteraction: "",
    //   },
    //   {
    //     id: 20,
    //     pspreference: "W56MHZFPW5PFWR82",
    //     eventcode: "AUTHORISATION",
    //     merchantreference: "f3fc0b2a-c3b5-45ca-a4ee-b5622360d293",
    //     shopperreference: "",
    //     timestamp: "2023-03-02T14:46:05.101+00:00",
    //     merchantaccount: "RochusOffermanECOM",
    //     paymentmethod: "eps",
    //     amount: "1000",
    //     currency: "EUR",
    //     success: "false",
    //     refusalreasonraw: "",
    //     networktxreference: "",
    //     liabilityshift: "",
    //     threedsversion: "",
    //     threedauthenticated: "",
    //     threedauthenticatedresponse: "",
    //     threedoffered: "",
    //     threedofferedresponse: "",
    //     expirydate: "",
    //     cardbin: "",
    //     cardsummary: "",
    //     issuercountry: "",
    //     fundingsource: "",
    //     metadata: "",
    //     iban: "",
    //     shopperemail: "",
    //     shopperinteraction: "",
    //   },
    //   {
    //     id: 19,
    //     pspreference: "T3X9Q4V4QGNG5S82",
    //     eventcode: "AUTHORISATION",
    //     merchantreference: "176aa3f0-36ec-4219-8cce-743473ef8fc9",
    //     shopperreference: "",
    //     timestamp: "2023-03-02T08:17:47.910+00:00",
    //     merchantaccount: "RochusOffermanECOM",
    //     paymentmethod: "visa",
    //     amount: "1000",
    //     currency: "EUR",
    //     success: "true",
    //     refusalreasonraw: "AUTHORISED",
    //     networktxreference: "223314717137606",
    //     liabilityshift: "false",
    //     threedsversion: "1.0.2",
    //     threedauthenticated: "false",
    //     threedauthenticatedresponse: "N/A",
    //     threedoffered: "true",
    //     threedofferedresponse: "U",
    //     expirydate: "03/2030",
    //     cardbin: "411111",
    //     cardsummary: "1111",
    //     issuercountry: "NL",
    //     fundingsource: "",
    //     metadata: "",
    //     iban: "",
    //     shopperemail: "",
    //     shopperinteraction: "",
    //   },
    //   {
    //     id: 18,
    //     pspreference: "W74SMPCX2TGLNK82",
    //     eventcode: "AUTHORISATION",
    //     merchantreference: "bb3b46d2-5981-48bd-9d37-f15874180d08",
    //     shopperreference: "",
    //     timestamp: "2023-03-02T08:16:42.239+00:00",
    //     merchantaccount: "RochusOffermanECOM",
    //     paymentmethod: "mc",
    //     amount: "1000",
    //     currency: "EUR",
    //     success: "true",
    //     refusalreasonraw: "AUTHORISED",
    //     networktxreference: "NFGHMYG1W0302",
    //     liabilityshift: "true",
    //     threedsversion: "2.2.0",
    //     threedauthenticated: "true",
    //     threedauthenticatedresponse: "Y",
    //     threedoffered: "true",
    //     threedofferedresponse: "Y",
    //     expirydate: "03/2030",
    //     cardbin: "520128",
    //     cardsummary: "9736",
    //     issuercountry: "RU",
    //     fundingsource: "",
    //     metadata: "",
    //     iban: "",
    //     shopperemail: "",
    //     shopperinteraction: "",
    //   },
    //   {
    //     id: 17,
    //     pspreference: "ZQ6B93R7JV5X8N82",
    //     eventcode: "AUTHORISATION",
    //     merchantreference: "bd07d817-dfe8-45c4-85c7-44a072863c6b",
    //     shopperreference: "",
    //     timestamp: "2023-03-02T08:16:17.996+00:00",
    //     merchantaccount: "RochusOffermanECOM",
    //     paymentmethod: "visa",
    //     amount: "1000",
    //     currency: "EUR",
    //     success: "true",
    //     refusalreasonraw: "AUTHORISED",
    //     networktxreference: "200852069169037",
    //     liabilityshift: "false",
    //     threedsversion: "1.0.2",
    //     threedauthenticated: "false",
    //     threedauthenticatedresponse: "N/A",
    //     threedoffered: "true",
    //     threedofferedresponse: "U",
    //     expirydate: "03/2030",
    //     cardbin: "411111",
    //     cardsummary: "1111",
    //     issuercountry: "NL",
    //     fundingsource: "",
    //     metadata: "",
    //     iban: "",
    //     shopperemail: "",
    //     shopperinteraction: "",
    //   },
    //   {
    //     id: 16,
    //     pspreference: "DBCGKQC6L8NKGK82",
    //     eventcode: "AUTHORISATION",
    //     merchantreference: "167306c7-b3cc-4168-93be-a99278e1f0c6",
    //     shopperreference: "",
    //     timestamp: "2023-03-01T22:03:32.786+00:00",
    //     merchantaccount: "RochusOffermanECOM",
    //     paymentmethod: "visa",
    //     amount: "1000",
    //     currency: "EUR",
    //     success: "true",
    //     refusalreasonraw: "AUTHORISED",
    //     networktxreference: "620968428202826",
    //     liabilityshift: "false",
    //     threedsversion: "1.0.2",
    //     threedauthenticated: "false",
    //     threedauthenticatedresponse: "N/A",
    //     threedoffered: "true",
    //     threedofferedresponse: "U",
    //     expirydate: "03/2030",
    //     cardbin: "411111",
    //     cardsummary: "1111",
    //     issuercountry: "NL",
    //     fundingsource: "",
    //     metadata: "",
    //     iban: "",
    //     shopperemail: "",
    //     shopperinteraction: "",
    //   },
    // ],
    recharge: [],
  },
  reducers: {
    paymentNotifications: (state, action) => {
      const [response, status] = action.payload;
      if (status >= 300) {
        state.error = "Error";
      } else {
        state.paymentNotifications = response.rows;
      }
    },
    balanceNotification: (state, action) => {
      const [response, status] = action.payload;
      if (status >= 300) {
        state.error = "Error";
      } else {
        state.balanceNotifications = response.rows;
      }
    },
    notificationItem: (state, action) => {
      state.paymentNotificationItem = action.payload.id;
    },
    balanceNotificationItem: (state, action) => {
      state.balanceNotificationItem = action.payload.id;
    },
  },
});

export const databaseActions = databaseSlice.actions;

export const paymentNotifications = () => async (dispatch) => {
  const response = await fetch(`/paymentsNotification`, {
    method: "GET",
    headers: {
      "Content-Type": "application/json",
    },
  });
  dispatch(
    databaseActions.paymentNotifications([
      await response.json(),
      response.status,
    ])
  );
};

export const balanceNotifications = () => async (dispatch) => {
  console.log('test');
  const response = await fetch(`/balanceNotification`, {
    method: "GET",
    headers: {
      "Content-Type": "application/json",
    },
  });
  dispatch(
    databaseActions.balanceNotification([
      await response.json(),
      response.status,
    ])
  );
};

export default databaseSlice;
